dashboard/urls.py
from django.urls import path
from . import views

app_name='dashboard'
urlpatterns=[
    path('',views.index,name='dashboard')
]

homepage/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import logInForm

app_name= 'homepage'

urlpatterns=[
    path('',views.index,name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='homepage/login.html', authentication_form=logInForm),name='login'),
    path('logout/',views.logout,name='logout')
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns=[
    path('',views.browse,name='browse'),
    path('new/',views.new,name='new'),
    path('<int:pk>', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),

]

message/urls.py
from django.urls import path

from . import views

app_name='message'

urlpatterns=[
    path('inbox/',views.inbox, name='inbox'),
    path('<int:pk>/',views.detail,name='pm'),
    path('new/<int:item_pk>/',views.new_message,name='new')
]

myweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('homepage.urls')),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('message.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class signUpForm(UserCreationForm):
    class Meta:
        model=User
        fields= ('username','email','password1','password2')

    username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class':'w-3/4 ms-12 py-4 px-6 rounded-lg'
    }))
    email=forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder':'Email@example.example',
        'class': 'w-3/4 ms-12 py-4 px-6 rounded-lg'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-3/4 ms-12 py-4 px-6 rounded-lg'
    }))
    password2=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Repeated Password',
        'class': 'w-3/4 ms-12 py-4 px-6 rounded-lg'
    }))

class logInForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'w-3/4 ms-12 py-4 px-6 rounded-lg'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-3/4 ms-12 py-4 px-6 rounded-lg'
    }))

homepage/views.py
from django.contrib import auth
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import signUpForm
# Create your views here.

def index(request):
    items=Item.objects.order_by('-created_at').filter(is_sold=False)[0:8]
    categories=Category.objects.all()
    return render(request,'homepage/index.html',{'categories':categories,
                                                 'items':items})

def contact(request):
    return render(request,'homepage/contact.html')

def signup(request):
    if request.method=='POST':
        form=signUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = signUpForm()

    return render(request,'homepage/signup.html',{
        'form':form
    })

def logout(request):
    auth.logout(request)
    return redirect('homepage:index')

homepage/templates/homepage/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    this project is made by Ellnaz Aliabadi for my final django project
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>
    {% block title %}
    {% endblock %}
    | My Shop
    </title>
</head>
<body class="bg-sky-50">
    <nav class="sticky top-0 left-0 right-0 py-6 px-6 flex justify-between items-center bg-slate-900 text-white">
        <div class="space-x-6">
            <a href="{% url 'homepage:index' %}" class="text-2xl font-semibold">Home</a>
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-green-300">New Item</a>
            <a href="{% url 'item:browse' %}" class="text-lg font-semibold hover:text-green-300">Browse</a>
        </div>
        <div class="space-x-4 flex justify-between items-center">
            <form action="{% url 'item:browse' %}" method="get">
              <input name="query" style="min-width: 300px" class="px-2 py-2 bg-gray-100 rounded-lg text-gray-500" type="text" value="{{ query }}" placeholder="Search" aria-label="Search">
              <button class="px-4 py-2 text-md font-semibold bg-gray-700 text-white rounded-xl hover:bg-cyan-400" type="submit">Search</button>
            </form>
        </div>
        {% if request.user.is_authenticated %}
            <div class="space-x-5 tex-white flex">
                <a class="mt-3 text-lg font-semibold hover:text-green-300" href="{% url 'message:inbox' %}">Inbox</a>
                <a class="mt-3 text-lg font-semibold hover:text-green-300" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
                <form action="{% url 'homepage:logout' %}" method="post">
                    {% csrf_token %}
                    <button class="px-6 py-3 text-lg font-semibold bg-gray-700 text-white rounded-xl hover:bg-green-300" type="submit">Log Out</button>
                </form>
            </div>
            {% else %}
            <div class="">
                <a class="px-6 py-3 text-lg font-semibold bg-gray-700 text-white rounded-xl hover:bg-cyan-400" href="{% url 'homepage:login' %}">Log in</a>
                <span class="text-sm font-semibold text-gray-400">or</span>
                <a href="{% url 'homepage:signup' %}" class="px-6 py-3 text-lg font-semibold bg-green-300 text-black rounded-xl hover:bg-cyan-400">Sign up</a>
            </div>
          {% endif %}
    </nav>
    <div class="px-6 py-6">
        {% block content %}

        {% endblock %}
    </div>
    <footer class="items-center text-white bg-slate-900">
    <div class="items-center">
      <section class="mt-5">
        <div class="flex justify-around py-6">
          <div class="col-md-2">
            <h6 class="text-uppercase font-weight-bold">
              <a href="{% url 'item:browse' %}" class="text-white hover:text-green-300 text-semibold">Products</a>
            </h6>
          </div>

          <div class="col-md-2">
            <h6 class="text-uppercase font-weight-bold">
              <a href="#" class="text-white hover:text-green-300 text-semibold">Help</a>
            </h6>
          </div>

          <div class="col-md-2">
            <h6 class="text-uppercase font-weight-bold">
              <a href="{% url 'homepage:contact' %}" class="text-white hover:text-green-300 text-semibold">Contact</a>
            </h6>
          </div>

          <div class="col-md-2">
            <h6 class="text-uppercase font-weight-bold">
              <a href="https://github.com/angelii-ii" class="text-white hover:text-green-300 text-semibold">Made By</a>
            </h6>
          </div>

        </div>
      </section>
      <hr class="my-5 py-4" />
      <section class="py-8">
        <div class="flex justify-center text-cyan-400">
          <div>
            <p>
              Django final project by <a href="">Elnaz Aliabadi</a>
            </p>
          </div>
        </div>
      </section>
    </div>
  </footer>
</body>
</html>

homepage/templates/homepage/contact.html
{% extends 'homepage/base.html' %}

{% block title %}
    contact
{% endblock %}

{% block content %}
    <div class="w-1/2 mx-auto bg-emerald-300 p-8 rounded-xl">
        <h1 class="text-3xl font-bold mb-6">This site is made by: <span class="text-cyan-700 font-semibold text-2xl">Elnaz Aliabadi</span></h1>
        <h1 class="text-2xl font-bold mb-6">For my final Django project</h1>
        <h1 class="text-2xl font-bold mb-6">Feel free to check out my <a class="text-sky-600" href="https://github.com/angelii-ii">github</a>!!!</h1>
        <h1 class="text-lg font-bold mb-6 text-cyan-500">I'm probably not very active there though :( sorry</h1>
    </div>
{% endblock %}

homepage/templates/homepage/index.html
{% extends 'homepage/base.html' %}

{% block title %}
    Homepage
{% endblock %}

{% block content %}
    <div class="mt-6 px-4 py-10 bg-slate-400 rounded-lg">
        <h2 class="text-3xl mb-12 font-semibold">Newest Items</h2>
        <div class="grid grid-cols-4 gap-2">
            {% for i in items %}
                <div style="max-width: 20rem" class="bg-white hover:bg-green-300 rounded-xl mb-6">
                    <a href="{% url 'item:detail' i.id %}">
                        <div class="items-center rounded-t-xl" style="overflow: hidden">
                            <img class="mx-auto" style="max-height: 250px;object-fit: contain" src="{{ i.image.url }}" alt="">
                        </div>
                        <div class="p-6 rounded-b-xl">
                            <h3 class="text-2xl font-bold">{{ i.name }}</h3>
                            <p class="text-md text-blue-600">{{ i.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="mt-6 px-4 py-10 bg-slate-400 rounded-lg">
        <h2 class="text-3xl mb-12 font-semibold">Categories</h2>
        <div style="max-height: 350px" class="grid grid-cols-4 gap-3 overflow-y-scroll">
            {% for category in categories %}
                <div style="min-width: 200px">
                    <a style="margin: 5px 10px" href="{% url 'item:browse' %}?query={{ query }}&category={{ category.id }}">
                        <div class="p-6 rounded-xl bg-white hover:bg-cyan-300">
                            <p class="text-2xl font-bold">{{ category.name }}</p>
                            <p class="text-lg text-blue-600">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

homepage/templates/homepage/login.html
{% extends 'homepage/base.html' %}

{% block title %}
    Log in
{% endblock %}

{% block content %}
    <div style="width: 650px" class="w-1/2 my-6 mx-auto bg-zinc-200 rounded-2xl py-8 px-5">
        <h1 class="mb-7 text-3xl font-semibold">Log in</h1>
        <form action="." method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-3">Username:</label></br>{{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-3">Password:</label></br>{{ form.password }}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-7 bg-red-100 rounded-lg">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
            {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class=" ms-12 mt-6 py-4 px-8 text-lg bg-cyan-400 hover:bg-cyan-600 rounded-lg text-white" type="submit" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

homepage/templates/homepage/signup.html
{% extends 'homepage/base.html' %}

{% block title %}
    Sign Up
{% endblock %}

{% block content %}
    <div style="width: 650px" class="w-1/2 my-6 mx-auto bg-zinc-200 rounded-2xl py-8 px-5">
        <h1 class="mb-7 text-3xl font-semibold">Sign Up</h1>
        <form action="." method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-3">Username:</label></br>{{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-3">Email:</label></br>{{ form.email }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-3">Password:</label></br>{{ form.password1 }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-3">Repeat Password:</label></br>{{ form.password2 }}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-7 bg-red-100 rounded-lg">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
            {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="ms-12 mt-6 py-4 px-8 text-lg bg-green-400 hover:bg-green-600 rounded-lg text-white" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}