item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns=[
    path('',views.browse,name='browse'),
    path('new/',views.new,name='new'),
    path('<int:pk>', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),

]

message/urls.py
from django.urls import path

from . import views

app_name='message'

urlpatterns=[
    path('inbox/',views.inbox, name='inbox'),
    path('<int:pk>/',views.detail,name='pm'),
    path('new/<int:item_pk>/',views.new_message,name='new')
]

myweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('homepage.urls')),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('message.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name=models.CharField(max_length=250,verbose_name='نام')

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Item(models.Model):
    category=models.ForeignKey(Category,related_name='items',on_delete=models.CASCADE)
    name=models.CharField(max_length=250,verbose_name='نام محصول')
    description=models.TextField(blank=True,null=True,verbose_name='توضیحات')
    price=models.FloatField()
    image=models.ImageField(upload_to='item_images',blank=True,null=True)
    is_sold=models.BooleanField(default=False)
    created_by= models.ForeignKey(User,related_name='items',on_delete=models.CASCADE)
    created_at=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES= 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'category')
        widgets= {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
            'class': INPUT_CLASSES
             }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
         }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image','is_sold')
        widgets= {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
            'class': INPUT_CLASSES
             }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
         }

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render,get_object_or_404,redirect
from .models import Category, Item
from .forms import NewItemForm,EditItemForm

def browse(request):
    query= request.GET.get('query','')
    category_id= request.GET.get('category',0)
    categories= Category.objects.all
    items= Item.objects.filter(is_sold=False)

    if category_id:
        items=items.filter(category_id=category_id)
    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request,'item/browse.html',{
        'items':items,
        'query':query,
        'categories':categories,
        'category_id': int(category_id)
    })

def detail(request, pk):
    item=get_object_or_404(Item,pk=pk)
    related_items= Item.objects.filter(category= item.category,is_sold=False).exclude(pk=pk)[0:4]
    return render(request, 'item/detail.html', {
        'item':item,
        'related_items':related_items
    })

@login_required
def new(request):
    if request.method == 'POST':
        form=NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item= form.save(commit=False)
            item.created_by=request.user
            item.save()

            return redirect('item:detail',pk=item.id)
    else:
        form = NewItemForm()

    return render(request,'item/form.html',{'form':form,
                                            'title': 'new item'})

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form=EditItemForm(request.POST, request.FILES,instance=item)

        if form.is_valid():
            form.save()
            return redirect('item:detail',pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request,'item/form.html',{'form':form,
                                            'title': 'edit item'})

@login_required
def delete(request,pk):
    item= get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    return redirect('dashboard:dashboard')

item/templates/item/browse.html
{% extends 'homepage/base.html' %}

{% block title %}Items{% endblock %}

{% block content %}
    <div class="grid px-8 py-4 grid-cols-4 gap-5 bg-slate-400 rounded-xl">
        <div class="col-span-1">
            <p class="font-semibold mb-2 text-xl">Categories</p>
            <ul>
                {% for category in categories %}
                    <li class="p-2 rounded-lg hover:text-cyan-300 {% if category.id == category_id %} bg-green-300 {% endif %}">
                        <a href="{% url 'item:browse' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
            <hr class="my-6">
            <p class="font-semibold">Clear Filters</p>
            <ul>
                <li><a href="{% url 'item:browse' %}" class="mt-2 py-4 px-8 inline-block bg-rose-500 text-lg rounded-lg text-gray-100 font-semibold">Clear</a></li>
            </ul>
        </div>
        <div class="col-span-3">
            <div class="grid grid-cols-4 gap-2">
            {% for i in items %}
                <div style="max-width: 20rem" class="bg-white hover:bg-cyan-200 rounded-xl">
                    <a href="{% url 'item:detail' i.id %}">
                        <div class="items-center rounded-t-xl">
                            <img class="mx-auto" style="max-height: 250px;object-fit: contain" src="{{ i.image.url }}" alt="">
                        </div>
                        <div class="p-6 rounded-b-xl">
                            <h3 class="text-2xl font-bold">{{ i.name }}</h3>
                            <p class="text-md text-blue-600">{{ i.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        </div>
    </div>
{% endblock %}

item/templates/item/detail.html
{% extends 'homepage/base.html' %}

{% block title %}
    {{ item.name }} details
{% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-2 p-6 bg-cyan-200 rounded-2xl">
            <h1 class="mb-6 text-3xl font-bold">{{ item.name }}</h1>
            <p class="text-indigo-900 mb-6"><strong>Seller:</strong> {{ item.created_by.username }}</p>
            <p class="text-indigo-900 mb-6"><strong>Price:</strong> {{ item.price }}</p>
            <p class="text-indigo-900 mb-6"><strong>Description:</strong></p>
            <div class="bg-cyan-100 p-8 rounded-lg">
            {% if item.description %}
                <p class="text-green-800">{{ item.description }}</p>
                {% else %}
                    <p class="text-blue-500">the seller didn't provide a description</p>
            {% endif %}
            </div>

            {% if request.user == item.created_by %}
                <div class="mt-6 p-6 bg-emerald-300 rounded-lg">
                    <p>your item</p>
                    <a class="inline-block mt-4 px-6 py-3 text-lg font-semibold bg-orange-300 text-white rounded-lg" href="{% url 'item:edit' item.id %}">Edit</a>
                    <a class="inline-block mt-4 px-6 py-3 text-lg font-semibold bg-rose-500 text-white rounded-lg" href="{% url 'item:delete' item.id %}">Delete</a>
                </div>
                {% else %}
                <a class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-lime-500 text-white hover:bg-lime-600 rounded-lg mx-auto" href="{% url 'message:new' item.id %}">Contact Seller</a>
            {% endif %}
        </div>
        <div class="col-span-3">
            <img style="max-height: 550px" src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-xl mx-auto">
        </div>
    </div>
    <div class="mt-6 px-4 py-10 bg-zinc-200 rounded-lg">
        <h2 class="text-3xl mb-12 font-semibold">Related Items</h2>
        <div class="grid grid-cols-4 gap-2">
            {% for item in related_items %}
                <div style="max-width: 18rem" class="bg-white hover:bg-pink-200 rounded-xl">
                    <a href="{% url 'item:detail' item.id %}">
                        <div class="items-center rounded-t-xl">
                            <img class="rounded-t-xl" src="{{ item.image.url }}" alt="">
                        </div>
                        <div class="p-6 rounded-b-xl">
                            <h3 class="text-2xl font-bold">{{ item.name }}</h3>
                            <p class="text-md text-blue-400">{{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

item/templates/item/form.html
{% extends 'homepage/base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1 class="mb-5 text-3xl ">{{ title }}</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="space-y-4">
            {{ form.as_p }}
        </div>
        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-7 bg-red-100 rounded-lg">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
            {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="mt-6 py-4 px-8 text-lg bg-green-300 hover:bg-emerald-600 rounded-lg text-white" type="submit">Submit</button>
    </form>
{% endblock %}